name: flutter_deep_dive
description: Improve flutter skills

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.10.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  go_router: ^7.0.2
  flutter_riverpod: ^2.3.6
  rive_splash_screen: ^0.1.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  freezed_annotation: ^2.4.1
  connectivity_plus: ^3.0.0
  flutter_zoom_drawer: ^3.1.1
  dio: ^5.2.1+1
  built_collection: ^5.1.1
  flutter_widget_from_html: ^0.10.4
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: any
  freezed: any
  json_serializable: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash/
    - assets/json_util/
    - assets/images/patterns/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  main_locale: en_US
  enabled: true
