// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA31U4OZJHcT4KvkIyd2T0q3FaG4pQW6_c',
    appId: '1:853811735380:web:7fdaa3433da1d78702b6c1',
    messagingSenderId: '853811735380',
    projectId: 'flutter-deep-dive',
    authDomain: 'flutter-deep-dive.firebaseapp.com',
    storageBucket: 'flutter-deep-dive.appspot.com',
    measurementId: 'G-ZZLNKSZFPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWZ2MPN70PlsL-xVni-NNdFPfNSWN8kLs',
    appId: '1:853811735380:android:26d779a97fe2af8502b6c1',
    messagingSenderId: '853811735380',
    projectId: 'flutter-deep-dive',
    storageBucket: 'flutter-deep-dive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3HbPPq3DVdwfFgzE-KB3uOHUrFuA8Q2w',
    appId: '1:853811735380:ios:006092bf9397dc3a02b6c1',
    messagingSenderId: '853811735380',
    projectId: 'flutter-deep-dive',
    storageBucket: 'flutter-deep-dive.appspot.com',
    iosClientId:
        '853811735380-3t8a2ac88e458846pv2ngjrap4v6ct4u.apps.googleusercontent.com',
    iosBundleId: 'com.viktor.deepdive.flutterDeepDive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3HbPPq3DVdwfFgzE-KB3uOHUrFuA8Q2w',
    appId: '1:853811735380:ios:006092bf9397dc3a02b6c1',
    messagingSenderId: '853811735380',
    projectId: 'flutter-deep-dive',
    storageBucket: 'flutter-deep-dive.appspot.com',
    iosClientId:
        '853811735380-3t8a2ac88e458846pv2ngjrap4v6ct4u.apps.googleusercontent.com',
    iosBundleId: 'com.viktor.deepdive.flutterDeepDive',
  );
}
